name: generate-badges
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3
      
    - name: Setup Node Js
      uses: actions/setup-node@v3
      with:
          node-version: '18'

    - name: Install cross-env
      run: npm install cross-env -D

    - name: Tests
      run: npm run test-ci
      
    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
          branches: master,preprod,staging